parameters:
  kernel.root_dir: ''

services:
    sonata.admin.generator:
      class: SonataGenerator\Service\SonataAdminGenerator
      arguments: ['@twig', '%sonata_generator.path_to_admin_yaml%']

    SonataGenerator\Command\GenerateSonataAdminCommand:
      arguments: ['@monolog.logger.console', '@sonata.admin.generator', '%kernel.root_dir%']
      tags:
            - { name: 'console.command', command: 'generate:sonata-admin' }

